filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    parsers:
      - ndjson:
          keys_under_root: true
          overwrite_keys: true
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
      - drop_event:
          when:
            not:
              or:
                - regexp:
                    container.name: "proxy.*"
                - regexp:
                    container.name: "auth.*"
                - regexp:
                    container.name: "cacher.*"
                - regexp:
                    container.name: "ratelimiter.*"
                - regexp:
                    container.name: "rules-engine.*"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
