env: "local"
http_server:
  address: "0.0.0.0:8080"
  timeout: 4s
  idle_timeout: 60s
  user: "user"
  password: "password"

ratelimiter_url: "http://ratelimiter:8081/rate_limit"
cacher_url: "http://cacher:8082/cache"
rules_engine_url: "http://rules-engine:8084"