env: "local"
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
  user: "user"
  password: "password"

resources:
  - name: Server1
    endpoint: /server1
    host: "http://localhost:9001"
  - name: Server2
    endpoint: /server2
    host: "http://localhost:9002"
  - name: Server3
    endpoint: /server3
    host: "http://localhost:9003"